// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: global_index.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalIndexEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GlobalIndexEntry) Reset() {
	*x = GlobalIndexEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalIndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalIndexEntry) ProtoMessage() {}

func (x *GlobalIndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_global_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalIndexEntry.ProtoReflect.Descriptor instead.
func (*GlobalIndexEntry) Descriptor() ([]byte, []int) {
	return file_global_index_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalIndexEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GlobalIndexEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GlobalIndexMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*GlobalIndexEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GlobalIndexMap) Reset() {
	*x = GlobalIndexMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalIndexMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalIndexMap) ProtoMessage() {}

func (x *GlobalIndexMap) ProtoReflect() protoreflect.Message {
	mi := &file_global_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalIndexMap.ProtoReflect.Descriptor instead.
func (*GlobalIndexMap) Descriptor() ([]byte, []int) {
	return file_global_index_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalIndexMap) GetEntries() []*GlobalIndexEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_global_index_proto protoreflect.FileDescriptor

var file_global_index_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x3d, 0x0a, 0x0e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d,
	0x61, 0x70, 0x12, 0x2b, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79,
	0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x6b, 0x76, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_index_proto_rawDescOnce sync.Once
	file_global_index_proto_rawDescData = file_global_index_proto_rawDesc
)

func file_global_index_proto_rawDescGZIP() []byte {
	file_global_index_proto_rawDescOnce.Do(func() {
		file_global_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_index_proto_rawDescData)
	})
	return file_global_index_proto_rawDescData
}

var file_global_index_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_global_index_proto_goTypes = []interface{}{
	(*GlobalIndexEntry)(nil), // 0: GlobalIndexEntry
	(*GlobalIndexMap)(nil),   // 1: GlobalIndexMap
}
var file_global_index_proto_depIdxs = []int32{
	0, // 0: GlobalIndexMap.entries:type_name -> GlobalIndexEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_global_index_proto_init() }
func file_global_index_proto_init() {
	if File_global_index_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_global_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalIndexEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalIndexMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_index_proto_goTypes,
		DependencyIndexes: file_global_index_proto_depIdxs,
		MessageInfos:      file_global_index_proto_msgTypes,
	}.Build()
	File_global_index_proto = out.File
	file_global_index_proto_rawDesc = nil
	file_global_index_proto_goTypes = nil
	file_global_index_proto_depIdxs = nil
}
